// data.js
const tableData = [
    {
      companyName: "ABC Corp",
      phoneNo: "123-456-7890",
      businessType: "IT Services",
      requirement: "Web Development",
      source: "LinkedIn",
      location: "New York",
      website: "www.abccorp.com",
      email: "info@abccorp.com",
      budget: "$5000",
    },
    {
      companyName: "XYZ Ltd",
      phoneNo: "987-654-3210",
      businessType: "Marketing",
      requirement: "SEO",
      source: "Google",
      location: "San Francisco",
      website: "www.xyzltd.com",
      email: "contact@xyzltd.com",
      budget: "$3000",
    },
    {
      companyName: "Tech Solutions",
      phoneNo: "555-123-4567",
      businessType: "Software Development",
      requirement: "Mobile App",
      source: "Referral",
      location: "Los Angeles",
      website: "www.techsolutions.com",
      email: "support@techsolutions.com",
      budget: "$8000",
    },
    {
        companyName: "Tech Solutions",
        phoneNo: "555-123-4567",
        businessType: "Software Development",
        requirement: "Mobile App",
        source: "Referral",
        location: "Los Angeles",
        website: "www.techsolutions.com",
        email: "support@techsolutions.com",
        budget: "$8000",
      },
      {
        companyName: "Tech Solutions",
        phoneNo: "555-123-4567",
        businessType: "Software Development",
        requirement: "Mobile App",
        source: "Referral",
        location: "Los Angeles",
        website: "www.techsolutions.com",
        email: "support@techsolutions.com",
        budget: "$8000",
      },
      {
        companyName: "Tech Solutions",
        phoneNo: "555-123-4567",
        businessType: "Software Development",
        requirement: "Mobile App",
        source: "Referral",
        location: "Los Angeles",
        website: "www.techsolutions.com",
        email: "support@techsolutions.com",
        budget: "$8000",
      },
      {
        companyName: "Tech Solutions",
        phoneNo: "555-123-4567",
        businessType: "Software Development",
        requirement: "Mobile App",
        source: "Referral",
        location: "Los Angeles",
        website: "www.techsolutions.com",
        email: "support@techsolutions.com",
        budget: "$8000",
      },

      {
        companyName: "Tech Solutions",
        phoneNo: "555-123-4567",
        businessType: "Software Development",
        requirement: "Mobile App",
        source: "Referral",
        location: "Los Angeles",
        website: "www.techsolutions.com",
        email: "support@techsolutions.com",
        budget: "$8000",
      },
      {
        companyName: "Tech Solutions",
        phoneNo: "555-123-4567",
        businessType: "Software Development",
        requirement: "Mobile App",
        source: "Referral",
        location: "Los Angeles",
        website: "www.techsolutions.com",
        email: "support@techsolutions.com",
        budget: "$8000",
      },
      {
        companyName: "Tech Solutions",
        phoneNo: "555-123-4567",
        businessType: "Software Development",
        requirement: "Mobile App",
        source: "Referral",
        location: "Los Angeles",
        website: "www.techsolutions.com",
        email: "support@techsolutions.com",
        budget: "$8000",
      },
      {
        companyName: "Tech Solutions",
        phoneNo: "555-123-4567",
        businessType: "Software Development",
        requirement: "Mobile App",
        source: "Referral",
        location: "Los Angeles",
        website: "www.techsolutions.com",
        email: "support@techsolutions.com",
        budget: "$8000",
      },
  ];
  
  export default tableData;
  